last_updated: "May 28th, 2013"
author: 
  name: Aaron Halfaker
  email: aaron.halfaker@gmail.com
  url: http://halfaker.info

lang: en-us

"✔": "✔"
"?": "?"
"✗": "✗"
"⌛": "⌛"
"⌚": "⌚"
(no edit summary): (no edit summary)
(no comment): (no comment)

all: all
all events: all events
as: as

ambiguous: ambiguous
any page: any page
ascending: ascending

bad-faith: bad-faith
by: by
by user: by user

categorizations: categorizations
categorization history: categorization history
Categorize: Categorize
categorized: categorized
categorize this user based on their activity: categorize this user based on their activity
Checking for previous session...: Checking for previous session...
click here to log in.: click here to log in.
click here to log out.: click here to log out.
Click here to move this user to a categorized list: Click here to move this user to a categorized list
click here to view the categorization history for this user: click here to view the categorization history for this user
contribs: contribs
comment: comment

days since registration: days since registration
descending: descending
desirability: desirability

edits: edits
edits to: edits to

general discussion thread: general discussion thread
good-faith: good-faith

help: help
history: history

Interactive edit graph: Interactive edit graph
"Its unclear whether this editor is trying to be productive or not (or press #2)": "Its unclear whether this editor is trying to be productive or not (or press #2)"

last activity: last activity
leave a comment explaining your decision (optional): leave a comment explaining your decision (optional)
load up the list of newcomers: load up the list of newcomers
Loading...: Loading...
Logged in as: Logged in as
Log into your wiki account.: Log into your wiki account.
Log out of Snuggle?: Log out of Snuggle?
log in: log in
log out: log out

"new users that haven't been categorized yet": "new users that haven't been categorized yet"
new users that have been categorized as good-faith: new users that have been categorized as good-faith
new users that have been categorized as ambiguous: new users that have been categorized as ambiguous
new users that have been categorized as bad-faith: new users that have been categorized as bad-faith
newcomers with more than: newcomers with more than
Not logged in...: Not logged in...

Password: Password

Recent activity: Recent activity
registered: registered
registration date: registration date
reverted: reverted
reverted edits: reverted edits
revisions: revisions

self-reverted: self-reverted
Snuggle: Snuggle
Snuggler: Snuggler
sort in increasing order: sort in increasing order
sort in descreasing order: sort in descreasing order
sorted by: sorted by
start snuggle: start snuggle
server started: server started
server stopped: server stopped
system events: system events

talk: talk
Talk page activity: Talk page activity
This user has not been categorized yet.: This user has not been categorized yet.
This user is currently categorized as: This user is currently categorized as
"This user is at least trying to do something useful (or press #1)": "This user is at least trying to do something useful (or press #1)"
"This editor is trying to cause harm or be disruptive (or press #3)": "This editor is trying to cause harm or be disruptive (or press #3)"
total edits: total edits

uncategorized: uncategorized
user: user
user actions: user actions
Username: Username
Username and stats: Username and stats

views: views

You must log in before categorizing users.: You must log in before categorizing users.
your wiki username: your wiki username
your wiki password: your wiki password.
