last_updated: "May 5th, 2013"
author: 
  name: Aaron Halfaker
  email: aaron.halfaker@gmail.com
  url: http://halfaker.info

snuggle:
  name: Snuggle

snuggler:
  user: Snuggler
  Checking for previous session...: Checking for previous session...
  Logged in as: Logged in as
  Not logged in...: Not logged in...
  login:
    description: Log into your wiki account.
    label: log in
    tooltip: Click here to log in.
  logout:
    description: Log out of Snuggle?
    label: log out
    tooltip: Click here to log out.

filter_menu:
  categories:
    uncategorized:
      label: uncategorized
      tooltip: "New users that haven't been categorized yet"
    good-faith: 
      label: "✔ good-faith"
      tooltip: "New users that have been categorized as good-faith"
    ambiguous: 
      label: "? ambiguous"
      tooltip: "New users that have been categorized as ambiguous"
    bad-faith:
      label: "✗ bad-faith"
      tooltop: "New users that have been categorized as bad-faith"
  filters:
    newcomers with more than: newcomers with more than
    edits to: edits to
    any page: any page
    sorted by: sorted by
    ascending: 
      label: ascending
      tooltip: sort in increasing order
    descending:
      label: descending
      tooltip: sort in descreasing order

user: 
  info: 
    utc: 
      user: user
      talk: talk
      contribs: contribs
    registered: registered
    views: views
    revisions: revisions
    reverted: reverted
    self-reverted: self-reverted
  category:
    label: Categorize
    tooltip: "categorizes this user based on their activity"
    history: history
    good-faith:
      label: "✔"
      tooltip: "This user is at least trying to do something useful (or press #1)"
    ambiguous:
      label: "?"
      tooltip: "Its unclear whether this editor is trying to be productive or not (or press #2)"
    bad-faith:
      label: "✗"
      tooltip: "This editor is trying to cause harm or be disruptive (or press #3)"
    This user has not been categorized yet.: "This user has yet to be categorized yet."
  activity:
    edits: edits
    days since registration: days since registration
    diff: 
      reverted: reverted
      by: by
