last_updated: "May 5th, 2013"
author: 
  name: Aaron Halfaker
  email: aaron.halfaker@gmail.com
  url: http://halfaker.info

snuggle:
  name: Snuggle
  user: Snuggler

controls:
  categories:
    uncategorized: uncategorized
    good-faith: "✔ good-faith"
    ambiguous: "? ambiguous"
    bad-faith: "✗ bad-faith"
  filters:
    newcomers with more than: newcomers with more than
    edits to: edits to
    sorted by: sorted by
    ascending: ascending
    descending: descending

user: 
  info: 
    utc: 
      user: user
      talk: talk
      contribs: contribs
    registered: registered
    views: views
    revisions: revisions
    reverted: reverted
    self-reverted: self-reverted
  category:
    categorize: Categorize
    history: history
    good-faith:
      label: "✔"
      tooltip: "This user is at least trying to do something useful (or press #1)"
    ambiguous:
      label: "?"
      tooltip: "Its unclear whether this editor is trying to be productive or not (or press #2)"
    bad-faith:
      label: "✗"
      tooltip: "This editor is trying to cause harm or be disruptive (or press #3)"
    This user has not been categorized yet.: "This user has yet to be categorized yet."
  activity:
    edits: edits
    days since registration: days since registration
    diff: 
      reverted: reverted
      by: by
