last_updated: "May 11th, 2013"
author: 
  name: Aaron Halfaker
  email: aaron.halfaker@gmail.com
  url: http://halfaker.info

# The name of the MediaWiki installation we're running against.
name: English Wikipedia

# The protocol to use when linking to the MediaWiki web interface.  'https' is 
# preferred if possible. 
protocol: https

# The base domain for the MediaWiki installation.
domain: en.wikipedia.org

# The path to wiki pages and scripts on the server.  This is used for making API
# requests and for linking back to the wiki from the the user interface.
path:
  pages: /wiki/
  scripts: /w/
file:
  index: index.php
  api: api.php

# Parameters for making requests to the API.  Wikipedia's API requires that a 
# header be provided with all requests that identifies the originator of the 
# request.
requests:
  headers:
    User-Agent: "Snuggle system (see [[WP:Snuggle]])"

# String to append at the end of comments for all page edit actions performed.
# This is useful for directing other Wikipedians to Snuggle and for tracking 
# the use of Snuggle across the history of edits in the wiki.
comment_suffix: " ([[WP:Snuggle|Sn]])"


# Thread traces are how socially relevant actions are recorded.  Historically,
# the traces of actions relevant to a user and their behavior in Wikipedia have
# been captured on their talk page.  This section specifies a set of traces that 
# Snuggle will identify and present in the intergace.  Each "trace" specifies a 
# regular expression intended to match the pattern of text that identifies a 
# wiki trace.  Each section of a user's talk page (delimited
# by level 2 headers) will be processed and at most one thread trace can be
# discovered based on the priority.  Priority is determined by order.  Traces 
# that appear first will be prioritized before other traces that could 
# potentially match.
#
# priority: A list of the keys used below sorted by priority
# traces: A map of (key->trace_definition) pairs that describe traces and presentation.
#   expression: a regular expression to be used to check if the thread matches
#               the thread type.  In most cases, this is looking for something 
#               of the form "<!-- Template:... -->"
#   groups: for each group in the regular expression, the icon can be modified.
#           Current the only supported operation is to add a superscript.
#   icon:
#     display: Text to include within the icon
#     superscript: (optional) text to include in a superscript of the icon
#     tooltip: A tooltip that will appear when a user hovers over the trace's 
#              icon in the user interface.
#     style: css based coloring information to be applied to the icon.  Use this
#            to convey information about the meaning of the trace.  
#            e.g. warnings are black and red and welcomes are green and blue.
talk_threads:
  priority:
    - block
    - vandal warning
    - spam warning
    - copyright warning
    - general warning
    - deletion notification
    - csd notification
    - articles for creation
    - teahouse invitation
    - welcome message
  traces:
    block: #####################################################################
      expression: "Template:uw-[a-z0-9]*block"
      groups: []
      icon: 
        label: block
        tooltip: Block notification
        style:
          border-color: "#000"
          background-color: "#ccc"
          box-shadow-color: "#000"
    vandal warning: ############################################################
      expression: "Template:uw-vandalism([0-9]+)?"
      groups:
        - {superscript: "%(group)s"}
      icon: 
        label: vandal
        tooltip: Vandalism warning
        style:
          border-color: "#000"
          box-shadow-color: "#600"
          background-color: "#f66"
    spam warning: ##############################################################
      expression: "Template:uw-spam([0-9]+)?"
      groups:
        - {superscript: "%(group)s"}
      icon: 
        label: spam
        tooltip: Spam warning
        style:
          border-color: "#000"
          background-color: "#f66"
          box-shadow-color: "#600"
    copyright warning: #########################################################
      expression: "Template:uw-copyright(-([a-z]+))?([0-9]+)?"
      groups:
        - {} # No one cares
        - {} # No one cares
        - {superscript: "%(group)s"}
      icon:
        label: ©
        tooltip: Copyright warning
        style:
          border-color: "#000"
          background-color: "#bb0"
          box-shadow-color: "#660"
    general warning: ###########################################################
      expression: "Template:uw-"
      groups: [] # No groups in the expression
      icon:
        label: warn
        tooltip: General warning
        style:
          border-color: "#000"
          background-color: "#f66"
          box-shadow-color: "#600"
    deletion notification: #####################################################
      expression: "Template:(proposed del.*?|prod|afd|.*?delet.*?)"
      groups: []
      icon:
        label: del
        tooltip: Notification of deletion proposal
        style:
          border-color: "#aaf"
          background-color: "#fff"
          box-shadow-color: "#aaf"
    csd notification: ##########################################################
      expression: "Template.*?csd|db-|speedy"
      groups: []
      icon: 
        label: csd
        tooltip: Notification of speedy deletion
        style:
          border-color: "#bb0"
          background-color: "#ff0"
          box-shadow-color: "#bb0"
    articles for creation: #####################################################
      expression: "Template:afc"
      groups: [] # No groups in the expression
      icon:
        label: "afc"
        tooltip: Articles for Creation
        style:
          border-color: "#bb0"
          background-color: "#ff0"
          box-shadow-color: "#bb0"
    teahouse invitation: #######################################################
      expression: "Template:teahouse"
      groups: [] # No groups in the expression
      icon:
        label: TH
        tooltip: Teahouse invitation
        style:
          border-color: "#6d6"
          background-color: "#9f9"
          box-shadow-color: "#6d6"
    welcome message: ###########################################################
      expression: "Template:w-[a-z]+|welcome|First article"
      groups: [] # No groups in the expression
      icon:
        label: W
        tooltip: Welcome message
        style:
          border-color: "#66f"
          background-color: "#eef"
          box-shadow-color: "#66f"


# User actions represent actions that can be performed on wiki from Snuggle.  
# A good example of a common action is to post a message on the user's talk 
# page.  The order in which they are listed will determine how they appear in
# the user interface.
#
#display: Specifies which actions to display in the user interface.  Removing a
#         an action name from this list will effectively disable the action.
#actions: 
#   name: The name to be used for this field.  This will be used as a label in 
#          the user interface and also as an identifier within the system.
#   description: the preamble that appears before the form explaining what 
#                action will be taken.  Can contain wiki links and references 
#                to the user.
#   summary: this is used to represent the action taken when presenting the 
#            log of user actions performed.  Use %(user)s and %(snuggler)s to 
#            depict where each actor should be referenced.
#   fields: specifies the components of the form that will be presented in 
#          the UI.
#     type: the type of form field (text|textarea|select|option|check)
#     name: the identifier to be used for the form field (important for
#           string formatting)
#     label: the label that will appear next to the field in the user
#            interface.
#     default: (optional) an optional default value to be set for the
#              field.
#     options: (only relevant for radio and select fields) a set of
#              options for the user to select from.
#   operations: a set of actions to be performed on the wiki.
user_actions:
  display:
    - send message
    - invite to teahouse
    - report abuse
  actions:
    send message:
      label: send message
      description: >
        Posts a new message on 
        [[User:%(user_name)s|%(user_name)s]]'s 
        [[User_talk:%(user_name)s|talk page]].
      summary: "%(snuggler)s sent a message to %(user)s"
      fields:
        - # header
          name: header
          label: Header
          type: text
          tooltip: a header for the message
          default: "Hello %(user_name)s"
        - # message
          name: message
          label: Message
          type: textarea
          tooltip: the body of the message
      operations:
        - #Appends the message to the user's talk page
          type: append
          page_name: "User_talk:%(user_name)s"
          markup: "==%(header)s==\n%(message)s ~~~~"
          comment: "%(header)s"
    invite to teahouse:
      label: invite to teahouse
      description: >
        Posts an invitation to the [[WP:Teahouse]] on 
        [[User:%(user_name)s|%(user_name)s]]'s 
        [[User_talk:%(user_name)s|talk page]].
      summary: "%(snuggler)s invited %(user)s to the teahouse"
      fields:
        - # template
          name: template
          label: Template
          type: radio
          tooltip: the template to be used for the invitation.
          default: :Wikipedia:Teahouse/Invitation
          options:
            - # Standard invitation
              label: Invitation
              value: :Wikipedia:Teahouse/Invitation
              tooltip: The standard invitation template.
            - # Optional other invitiation style
              label: Invitation2
              value: :Wikipedia:Teahouse/Invitation2
              tooltip: An alternative invitation template.
        - # header
          name: header
          label: Header
          type: text
          tooltip: a header for the message
          default: "You're invited to the [[WP:Teahouse|Teahouse]]."
        - # message
          name: message
          label: Message
          type: textarea
          tooltip: the body of the message
      operations:
        - # Appends the template to the user's talk page
          type: append
          page_name: "User_talk:%(user_name)s"
          markup: "==%(header)s==\n{{subst%(template)s|message=%(message)s|sign=~~~~}}"
          comment: "%(header)s"
    report abuse:
      label: report abuse
      description: >
        Reports vandals and spammers to admins via the 
        [[WP:AIV|Administrator's notice board]]. Use only for
        <b>obvious</b> and <b>persistent</b> cases. Please review
        [[WP:Spam]], [[WP:Vandaism]] and the [[AIV Guide]].
      summary: "%(snuggler)s reported %(user)s to administrators"
      fields:
        - # reason
          name: reason
          type: "text"
          label: Reason for listing <small>(optional, keep it brief)</small>
          tooltip: the reason that %(user_name)s is being reported
      operations:
        - # Appends a list item to the bottom of AIV
          type: append
          page_name: Wikipedia:Administrator_intervention_against_vandalism
          markup: "* {{Vandal|%(user_name)s}} %(reason)s ~~~~"
          comment: "Reporting [[User:%(user_name)s]] for %(reason)s"

# Namespaces are configurable for MediaWiki installations.  This datastructure
# describes the configuration of the English Wikipedia.  Note that the Main 
# namespace has an empty prefix
namespaces:
  -2:
    name: Media
    prefixes:
      - "Media:"
  -1:
    name: Special
    prefixes:
      - "Special:"
  0:
    name: Articles
    prefixes:
      - ""
  1:
    name: Talk
    prefixes:
      - "Talk:"
  2:
    name: User
    prefixes:
      - "User:"
  3:
    name: User talk
    prefixes:
      - "User_talk:"
  4:
    name: Wikipedia
    prefixes:
      - "Wikipedia:"
      - "Project:"
      - "WP:"
  5:
    name: Wikipedia_talk
    prefixes:
      - "Wikipedia_talk:"
      - "Project_talk:"
      - "WT:"
  6:
    name: File
    prefixes:
      - "File:"
      - "Image:"
  7:
    name: File_talk
    prefixes:
      - "File_talk:"
      - "Image_talk:"
  8:
    name: Mediawiki
    prefixes:
      - "Mediawiki:"
  9:
    name: Mediawiki_talk
    prefixes:
      - "Mediawiki_talk:"
  10:
    name: Template
    prefixes:
      - "Template:"
  11:
    name: Template_talk
    prefixes:
      - "Template_talk:"
  12:
    name: Help
    prefixes:
      - "Help:"
  13:
    name: Help_talk
    prefixes:
      - "Help_talk:"
  14:
    name: Category
    prefixes:
      - "Category:"
  15:
    name: Category_talk
    prefixes:
      - "Category_talk:"
  100:
    name: Portal
    prefixes:
      - "Portal:"
  101:
    name: Portal_talk
    prefixes:
      Portal_talk
  108:
    name: Book
    prefixes:
      - "Book:"
  446:
    name: Education_program
    prefixes:
      - "Education_program:"
  447:
    name: Education_program_talk
    prefixes:
      - "Education_program_talk:"
  710:
    name: Timedtext
    prefixes:
      - "Timedtext:"
  711:
    name: Timedtext_talk
    prefixes:
      - "Timedtext_talk:"
  828:
    name: Module
    prefixes:
      - "Module:"
  829:
    name: Module_talk
    prefixes:
      - "Module_talk:"
