last_updated: "Jun 25th, 2013"
author: 
  name: Aaron Halfaker / Henrique Andrade
  email: aaron.halfaker@gmail.com / henriquedeandrade@gmail.com
  url: http://halfaker.info

# The name of the MediaWiki installation we're running against.
name: Wikipédia em português

# The protocol to use when linking to the MediaWiki web interface.  'https' is 
# preferred if possible. 
protocol: https

# The base domain for the MediaWiki installation.
domain: pt.wikipedia.org

# The path to wiki pages and scripts on the server.  This is used for making API
# requests and for linking back to the wiki from the the user interface.
path:
  pages: /wiki/
  scripts: /w/
file:
  index: index.php
  api: api.php

# Parameters for making requests to the API.  Wikipedia's API requires that a 
# header be provided with all requests that identifies the originator of the 
# request.
requests:
  headers:
    User-Agent: "Snuggle system (see [[WP:Snuggle]])"

# String to append at the end of comments for all page edit actions performed.
# This is useful for directing other Wikipedians to Snuggle and for tracking 
# the use of Snuggle across the history of edits in the wiki.
comment_suffix: " ([[WP:Snuggle|Sn]])"


# Thread traces are how socially relevant actions are recorded.  Historically,
# the traces of actions relevant to a user and their behavior in Wikipedia have
# been captured on their talk page.  This section specifies a set of traces that 
# Snuggle will identify and present in the intergace.  Each "trace" specifies a 
# regular expression intended to match the pattern of text that identifies a 
# wiki trace.  Each section of a user's talk page (delimited
# by level 2 headers) will be processed and at most one thread trace can be
# discovered based on the priority.  Priority is determined by order.  Traces 
# that appear first will be prioritized before other traces that could 
# potentially match.
#
# priority: A list of the keys used below sorted by priority
# traces: A map of (key->trace_definition) pairs that describe traces and presentation.
#   expression: a regular expression to be used to check if the thread matches
#               the thread type.  In most cases, this is looking for something 
#               of the form "<!-- Template:... -->"
#   groups: for each group in the regular expression, the icon can be modified.
#           Current the only supported operation is to add a superscript.
#   icon:
#     display: Text to include within the icon
#     superscript: (optional) text to include in a superscript of the icon
#     tooltip: A tooltip that will appear when a user hovers over the trace's 
#              icon in the user interface.
#     style: css based coloring information to be applied to the icon.  Use this
#            to convey information about the meaning of the trace.  
#            e.g. warnings are black and red and welcomes are green and blue.
talk_threads:
  priority:
    - block
    - vandal warning
    - spam warning
    - copyright warning
    - general warning
    - deletion notification
    - csd notification
    - welcome message
  traces:
    block: #####################################################################
      expression: "Predefinição:Bloqueado-disc"
      groups: []
      icon: 
        label: bloqueio
        tooltip: Notificação de bloqueio
        style:
          border-color: "#000"
          background-color: "#ccc"
          box-shadow-color: "#000"
    vandal warning: ############################################################
      expression: "Template:uw-vandalism([0-9]+)?"
      groups:
        - {superscript: "%(group)s"}
      icon: 
        label: vandalismo
        tooltip: Alerta de Vandalismo
        style:
          border-color: "#000"
          box-shadow-color: "#600"
          background-color: "#f66"
    spam warning: ##############################################################
      expression: "Predefinição:Propaganda"
      groups: []
      icon: 
        label: spam
        tooltip: Alerta de Spam
        style:
          border-color: "#000"
          background-color: "#f66"
          box-shadow-color: "#600"
    copyright warning: #########################################################
      expression: "\\[\\[Wikipédia:OTRS/Como enviar a permissão\\]\\]"
      groups: []
      icon:
        label: ©
        tooltip: Aviso de VDA
        style:
          border-color: "#000"
          background-color: "#bb0"
          box-shadow-color: "#660"
    general warning: ###########################################################
      expression: "Template:uw-huggle([0-9]+)"
      groups: 
        - {superscript: "%(group)s"}
      icon:
        label: alerta
        tooltip: Alerta geral
        style:
          border-color: "#000"
          background-color: "#f66"
          box-shadow-color: "#600"
    deletion notification: #####################################################
      expression: "\\[\\[Wikipedia:Eliminação por votação\\|eliminação por votação\\]\\]"
      groups: []
      icon:
        label: EV
        tooltip: Notificação de eliminação por votação
        style:
          border-color: "#aaf"
          background-color: "#fff"
          box-shadow-color: "#aaf"
    csd notification: ##########################################################
      expression: "Predefinição:Aviso-ER"
      groups: []
      icon: 
        label: ER
        tooltip: Notificação de eliminação rápida
        style:
          border-color: "#bb0"
          background-color: "#ff0"
          box-shadow-color: "#bb0"
    welcome message: ###########################################################
      expression: "Predefinição:Bem vindo"
      groups: [] # No groups in the expression
      icon:
        label: boas vindas
        tooltip: Mensagem de Boas vindas
        style:
          border-color: "#66f"
          background-color: "#eef"
          box-shadow-color: "#66f"


# User actions represent actions that can be performed on wiki from Snuggle.  
# A good example of a common action is to post a message on the user's talk 
# page.  The order in which they are listed will determine how they appear in
# the user interface.
#
#display: Specifies which actions to display in the user interface.  Removing a
#         an action name from this list will effectively disable the action.
#actions: 
#   name: The name to be used for this field.  This will be used as a label in 
#          the user interface and also as an identifier within the system.
#   description: the preamble that appears before the form explaining what 
#                action will be taken.  Can contain wiki links and references 
#                to the user.
#   summary: this is used to represent the action taken when presenting the 
#            log of user actions performed.  Use %(user)s and %(snuggler)s to 
#            depict where each actor should be referenced.
#   fields: specifies the components of the form that will be presented in 
#          the UI.
#     type: the type of form field (text|textarea|select|option|check)
#     name: the identifier to be used for the form field (important for
#           string formatting)
#     label: the label that will appear next to the field in the user
#            interface.
#     default: (optional) an optional default value to be set for the
#              field.
#     options: (only relevant for radio and select fields) a set of
#              options for the user to select from.
#   operations: a set of actions to be performed on the wiki.
user_actions:
  display:
    - send message
    - report abuse
  actions:
    send message:
      label: enviar mensagem
      description: >
        Enviar uma mensagem na
        [[Usuário(a)_Discussão:%(user_name)s|página de discussão]]
        de [[Usuário(a):%(user_name)s|%(user_name)s]].
      summary: "%(snuggler)s enviou uma mensagem para %(user)s"
      fields:
        - # header
          name: header
          label: Título
          type: text
          tooltip: um título para a mensagem
          default: "Olá %(user_name)s"
        - # message
          name: message
          label: Mensagem
          type: textarea
          tooltip: o corpo da mensagem
      operations:
        - #Appends the message to the user's talk page
          type: append
          page_name: "Usuário(a)_Discussão:%(user_name)s"
          markup: "==%(header)s==\n%(message)s ~~~~"
          comment: "%(header)s"
    report abuse:
      label: pedir bloqueio
      description: >
        Pedir bloqueios via 
        [[WP:AIV|Administrator's notice board]]. Use apenas para
        casos <b>óbvios</b> e <b>persistentes</b>.
      summary: "%(snuggler)s solicitou o bloqueio de %(user)s para os administradores"
      fields:
        - # reason
          name: reason
          type: "text"
          label: Indique sua razão<small>(seja sucinto)</small>
          tooltip: a razão pela qual %(user_name)s deve ser bloqueado
      operations:
        - # Appends a list item to the bottom of AIV
          type: append
          page_name: Wikipédia:Pedidos/Bloqueio
          markup: "{{subst:bloquear|%(user_name)s|2=%(reason)s}}"
          comment: "Solicitando bloqueio de [[User:%(user_name)s]] por %(reason)s"

# Namespaces are configurable for MediaWiki installations.  This datastructure
# describes the configuration of the English Wikipedia.  Note that the Main 
# namespace has an empty prefix
namespaces:
  -2:
    name: Multimédia
    prefixes:
      - "Multimédia:"
  -1:
    name: Domínio Especial
    prefixes:
      - "Especial:"
  0:
    name: Domínio Principal
    prefixes:
      - ""
  1:
    name: Página de Discussão
    prefixes:
      - "Discussão:"
  2:
    name: Página de usuário
    prefixes:
      - "Usuário(a):"
  3:
    name: Página de discussão do usuário
    prefixes:
      - "Usuário(a)_Discussão:"
  4:
    name: Domínio Wikipédia
    prefixes:
      - "Wikipédia:"
      - "Project:"
      - "WP:"
  5:
    name: Wikipédia Discussão
    prefixes:
      - "Wikipédia_Discussão:"
      - "Project_talk:"
      - "WT:"
  6:
    name: Ficheiro
    prefixes:
      - "Ficheiro:"
      - "Image:"
  7:
    name: Ficheiro Discussão
    prefixes:
      - "Ficheiro_Discussão:"
      - "Image_talk:"
  8:
    name: Domínio Mediawiki
    prefixes:
      - "Mediawiki:"
  9:
    name: MediaWiki Discussão
    prefixes:
      - "MediaWiki_Discussão:"
  10:
    name: Domínio Predefinição
    prefixes:
      - "Predefinição:"
  11:
    name: Predefinição Discussão
    prefixes:
      - "Predefinição_Discussão:"
  12:
    name: Domínio Ajuda
    prefixes:
      - "Ajuda:"
  13:
    name: Ajuda Discussão
    prefixes:
      - "Ajuda_Discussão:"
  14:
    name: Domínio Categoria
    prefixes:
      - "Categoria:"
  15:
    name: Categoria Discussão
    prefixes:
      - "Categoria_Discussão:"
  100:
    name: Domínio Portal
    prefixes:
      - "Portal:"
  101:
    name: Portal Discussão
    prefixes:
      - "Portal_Discussão:"
  102:
    name: Anexo
    prefixes:
      - "Anexo:"
  103:
    name: Anexo Discussão
    prefixes:
      - "Anexo_Discussão:"
  101:
    name: Portal Discussão
    prefixes:
      - "Portal_Discussão:"
  104:
    name: Domínio Livro
    prefixes:
      - "Livro:"
  105:
    name: Livro Discussão
    prefixes:
      - "Livro_Discussão:"
  828:
    name: Módulo Lua
    prefixes:
      - "Módulo:"
  829:
    name: Módulo Discussão
    prefixes:
      - "Módulo_Discussão:"
